name: globalpay
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  iconsax_plus: any
  phosphor_flutter: any
  smooth_page_indicator: any
  flutter_spinkit: any
  flutter_svg: any
  flutter_map: any
  latlong2: any
  image_picker: any
  confetti: any
  intl: any
  share_plus: any
  screenshot: any
  flutter_secure_storage: ^10.0.0
  pdf: any
  #  equatable: ^2.0.8
  printing: any
  http: ^1.6.0
  path_provider: any
  #  image_gallery_saver: ^2.0.3
  open_filex: any
  country_flags: any
  country_pickers: any
  #  media_store_plus: ^0.1.3
  fl_chart: any
  #  provider: any
  dropdown_search: ^5.0.6
  carousel_slider: any
  flip_card: any
  blur: any
  glassmorphism_ui: any
  intl_phone_field: any
  intl_phone_number_input: any
  pinput: any
  google_fonts: any
  dio: ^5.9.0
  #  http: any
  webview_flutter: any
  shared_preferences: any
  flutter_animate: any
  marquee: ^2.2.3
  reorderables: ^0.4.2
  glassmorphism: ^2.0.0
  qr_flutter: any
  provider: ^6.1.2
  mobile_scanner: any
  flutter_native_splash: ^2.4.0
  equatable: ^2.0.7
  lucide_icons_flutter: ^3.1.5
  #  gallery_saver: ^2.3.2
  mailer: ^6.6.0
  device_info_plus: ^12.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/png/globalpay_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/png/
    - assets/data/countries.json